In [23]:
import numpy as np

arr= np.array([1,2,3,4,5])
print(arr[1:])
arr.copy()
x=arr.view()
x[0]=0
print(x.base)
print(arr.base
     )

[2 3 4 5]
[0 2 3 4 5]
None


In [18]:
arr=np.array([1.2,3.2,4.3,5.4])
x=arr.astype("S")
print(arr)
print(x.dtype)

[1.2 3.2 4.3 5.4]
|S32


In [38]:
a=np.array([[1,2,3,4,5],[2,3,4,4,5],[3,4,5,5,2]])

for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [35]:
x=np.array([[1,2,3,4],[3,4,4,5]])
for i in x:
    for j in i:
        
        print(j)

1
2
3
4
3
4
4
5


In [33]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new=arr.reshape(2,3,2)
print(new.base)
for i in new:
    print (i)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [41]:
#join two or more array
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [49]:
#join two or more array
arr1=np.array([[1,2,3,4,5],[3,4,5,3,2]])
arr2=np.array([[6,7,8,9,10],[2,3,1,1,3]])
arr=np.dstack((arr1,arr2))
print(arr)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]

 [[ 3  2]
  [ 4  3]
  [ 5  1]
  [ 3  1]
  [ 2  3]]]


In [50]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,2,4,1,0,11,12,3])
new =np.array_split(arr,3)
print(new)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


In [51]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,2,4,1,0,11,12,3])
print(np.sort(arr))

[ 0  1  1  2  2  3  3  4  4  5  6  7  8  9 10 11 12]
